service: twenty-one-cen-backend
configValidationMode: off
frameworkVersion: '3'

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  serverless-offline:
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  binaryMediaTypes:
    - '*/*'
  environment:
    DEBUG: '*'
    NODE_ENV: ${self:provider.stage}
    MONGO_URL: ${file(env.yml):MONGO_URL}
    JWT_ACCESS_SECRET: ${file(env.yml):JWT_ACCESS_SECRET}
    JWT_ACCESS_TIME: ${file(env.yml):JWT_ACCESS_TIME}
    JWT_REFRESH_SECRET: ${file(env.yml):JWT_REFRESH_SECRET}
    JWT_REFRESH_TIME: ${file(env.yml):JWT_REFRESH_TIME}
    AWS_ACCESS_KEY_ID_2: ${file(env.yml):AWS_ACCESS_KEY_ID_2}
    AWS_ACCESS_KEY_SECRET_2: ${file(env.yml):AWS_ACCESS_KEY_SECRET_2}
    AWS_S3_BUCKET: ${file(env.yml):AWS_S3_BUCKET}

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
      - cors: true
